// ********RoostGPT********
/*
Test generated by RoostGPT for test testJ using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=createWindow_ae437130da
ROOST_METHOD_SIG_HASH=createWindow_bfe8572e87


*/

// ********RoostGPT********
const assert = require('assert');
const { createWindow } = require('./index');
const { BrowserWindow, app } = require('electron');

describe('createWindow', function() {
  let mainWindow;

  beforeEach(function() {
    mainWindow = createWindow();
  });

  afterEach(function() {
    mainWindow = null;
  });

  it('should create a new BrowserWindow', function() {
    assert(mainWindow instanceof BrowserWindow);
  });

  it('should set the correct properties on the window', function() {
    const expectedProperties = {
      width: 800,
      minWidth: 320,
      height: 600,
      fullscreenable: true,
      backgroundColor: "#403F4D",
      icon: path.join(app.getAppPath(), "assets/png/128x128.png"),
      webPreferences: {
        preload: path.join(app.getAppPath(), "dist/preload/index.cjs")
      }
    };

    const actualProperties = mainWindow.getBounds();
    assert.deepStrictEqual(actualProperties, expectedProperties);
  });

  it('should load the correct URL', function() {
    const expectedURL = isDev ? "http://localhost:5173" : new URL("../dist/renderer/index.html", "file://" + __dirname).toString();
    const actualURL = mainWindow.getURL();
    assert.strictEqual(actualURL, expectedURL);
  });
});
